# Generated by Django 5.2.9 on 2026-02-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='join_code',
            field=models.CharField(db_index=True, editable=False, max_length=64, unique=True),
        ),
    ]
