# Generated by Django 5.2.9 on 2026-02-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
    ]
