# Generated by Django 5.2.9 on 2026-02-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_picture',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
