# Generated by Django 5.2.9 on 2026-03-06 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('written', 'Written Answer')], max_length=20)),
                ('instruction', models.CharField(blank=True, help_text='Example: Choose one correct answer / Choose two correct answers.', max_length=255)),
                ('text', models.TextField()),
                ('prompt_image', models.URLField(blank=True, help_text='Optional image URL for visual questions.')),
                ('correct_answer', models.TextField(blank=True, help_text='Use mainly for written questions.')),
                ('required_choices_count', models.PositiveIntegerField(default=1, help_text='How many choices the user is expected to select for MCQ questions.')),
                ('points', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('level', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='examitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='examitem',
            name='exam',
        ),
        migrations.DeleteModel(
            name='FreeAnswerQuestion',
        ),
        migrations.RemoveField(
            model_name='multiplechoiceoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='readingfreeanswerquestion',
            name='reading',
        ),
        migrations.RemoveField(
            model_name='readingmultiplechoiceoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='readingmultiplechoicequestion',
            name='reading',
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='exam',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image representing the exam.', null=True, upload_to='exam_images/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='max_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='time_duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Duration of the exam in minutes.'),
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exams.question'),
        ),
        migrations.AddField(
            model_name='reading',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='question',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exams.reading'),
        ),
        migrations.DeleteModel(
            name='ExamItem',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceOption',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='ReadingFreeAnswerQuestion',
        ),
        migrations.DeleteModel(
            name='ReadingMultipleChoiceOption',
        ),
        migrations.DeleteModel(
            name='ReadingMultipleChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='ReadingPassage',
        ),
    ]
